
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module de1_soc_uart(
		// Clock pins
	CLOCK_50,
	CLOCK2_50,
	CLOCK3_50,
	CLOCK4_50,

	// ADC
	ADC_CS_N,
	ADC_DIN,
	ADC_DOUT,
	ADC_SCLK,

	// Audio
	AUD_ADCDAT,
	AUD_ADCLRCK,
	AUD_BCLK,
	AUD_DACDAT,
	AUD_DACLRCK,
	AUD_XCK,

	// SDRAM
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_LDQM,
	DRAM_RAS_N,
	DRAM_UDQM,
	DRAM_WE_N,

	// I2C Bus for Configuration of the Audio and Video-In Chips
	FPGA_I2C_SCLK,
	FPGA_I2C_SDAT,

	// 40-Pin Headers
	GPIO_0,
	GPIO_1,
	
	// Seven Segment Displays
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,

	// IR
	IRDA_RXD,
	IRDA_TXD,

	// Pushbuttons
	KEY,

	// LEDs
	LEDR,

	// PS2 Ports
	PS2_CLK,
	PS2_DAT,
	
	PS2_CLK2,
	PS2_DAT2,

	// Slider Switches
	SW,

	// Video-In
	TD_CLK27,
	TD_DATA,
	TD_HS,
	TD_RESET_N,
	TD_VS,

	// VGA
	VGA_B,
	VGA_BLANK_N,
	VGA_CLK,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_SYNC_N,
	VGA_VS,

	////////////////////////////////////
	// HPS Pins
	////////////////////////////////////
	
	// DDR3 SDRAM
	HPS_DDR3_ADDR,
	HPS_DDR3_BA,
	HPS_DDR3_CAS_N,
	HPS_DDR3_CKE,
	HPS_DDR3_CK_N,
	HPS_DDR3_CK_P,
	HPS_DDR3_CS_N,
	HPS_DDR3_DM,
	HPS_DDR3_DQ,
	HPS_DDR3_DQS_N,
	HPS_DDR3_DQS_P,
	HPS_DDR3_ODT,
	HPS_DDR3_RAS_N,
	HPS_DDR3_RESET_N,
	HPS_DDR3_RZQ,
	HPS_DDR3_WE_N,

	// Ethernet
	HPS_ENET_GTX_CLK,
	HPS_ENET_INT_N,
	HPS_ENET_MDC,
	HPS_ENET_MDIO,
	HPS_ENET_RX_CLK,
	HPS_ENET_RX_DATA,
	HPS_ENET_RX_DV,
	HPS_ENET_TX_DATA,
	HPS_ENET_TX_EN,

	// Flash
	HPS_FLASH_DATA,
	HPS_FLASH_DCLK,
	HPS_FLASH_NCSO,

	// Accelerometer
	HPS_GSENSOR_INT,
		
	// General Purpose I/O
	HPS_GPIO,
		
	// I2C
	HPS_I2C_CONTROL,
	HPS_I2C1_SCLK,
	HPS_I2C1_SDAT,
	HPS_I2C2_SCLK,
	HPS_I2C2_SDAT,

	// Pushbutton
	HPS_KEY,

	// LED
	HPS_LED,
		
	// SD Card
	HPS_SD_CLK,
	HPS_SD_CMD,
	HPS_SD_DATA,

	// SPI
	HPS_SPIM_CLK,
	HPS_SPIM_MISO,
	HPS_SPIM_MOSI,
	HPS_SPIM_SS,

	// UART
	HPS_UART_RX,
	HPS_UART_TX,

	// USB
	HPS_CONV_USB_N,
	HPS_USB_CLKOUT,
	HPS_USB_DATA,
	HPS_USB_DIR,
	HPS_USB_NXT,
	HPS_USB_STP
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

////////////////////////////////////
// FPGA Pins
////////////////////////////////////

// Clock pins
input						CLOCK_50;
input						CLOCK2_50;
input						CLOCK3_50;
input						CLOCK4_50;

// ADC
inout						ADC_CS_N;
output					ADC_DIN;
input						ADC_DOUT;
output					ADC_SCLK;

// Audio
input						AUD_ADCDAT;
inout						AUD_ADCLRCK;
inout						AUD_BCLK;
output					AUD_DACDAT;
inout						AUD_DACLRCK;
output					AUD_XCK;

// SDRAM
output 		[12: 0]	DRAM_ADDR;
output		[ 1: 0]	DRAM_BA;
output					DRAM_CAS_N;
output					DRAM_CKE;
output					DRAM_CLK;
output					DRAM_CS_N;
inout			[15: 0]	DRAM_DQ;
output					DRAM_LDQM;
output					DRAM_RAS_N;
output					DRAM_UDQM;
output					DRAM_WE_N;

// I2C Bus for Configuration of the Audio and Video-In Chips
output					FPGA_I2C_SCLK;
inout						FPGA_I2C_SDAT;

// 40-pin headers
inout			[35: 0]	GPIO_0;
inout			[35: 0]	GPIO_1;

// Seven Segment Displays
output		[ 6: 0]	HEX0;
output		[ 6: 0]	HEX1;
output		[ 6: 0]	HEX2;
output		[ 6: 0]	HEX3;
output		[ 6: 0]	HEX4;
output		[ 6: 0]	HEX5;

// IR
input						IRDA_RXD;
output					IRDA_TXD;

// Pushbuttons
input			[ 3: 0]	KEY;

// LEDs
output		[ 9: 0]	LEDR;

// PS2 Ports
inout						PS2_CLK;
inout						PS2_DAT;

inout						PS2_CLK2;
inout						PS2_DAT2;

// Slider Switches
input			[ 9: 0]	SW;

// Video-In
input						TD_CLK27;
input			[ 7: 0]	TD_DATA;
input						TD_HS;
output					TD_RESET_N;
input						TD_VS;

// VGA
output		[ 7: 0]	VGA_B;
output					VGA_BLANK_N;
output					VGA_CLK;
output		[ 7: 0]	VGA_G;
output					VGA_HS;
output		[ 7: 0]	VGA_R;
output					VGA_SYNC_N;
output					VGA_VS;



////////////////////////////////////
// HPS Pins
////////////////////////////////////
	
// DDR3 SDRAM
output		[14: 0]	HPS_DDR3_ADDR;
output		[ 2: 0]  HPS_DDR3_BA;
output					HPS_DDR3_CAS_N;
output					HPS_DDR3_CKE;
output					HPS_DDR3_CK_N;
output					HPS_DDR3_CK_P;
output					HPS_DDR3_CS_N;
output		[ 3: 0]	HPS_DDR3_DM;
inout			[31: 0]	HPS_DDR3_DQ;
inout			[ 3: 0]	HPS_DDR3_DQS_N;
inout			[ 3: 0]	HPS_DDR3_DQS_P;
output					HPS_DDR3_ODT;
output					HPS_DDR3_RAS_N;
output					HPS_DDR3_RESET_N;
input						HPS_DDR3_RZQ;
output					HPS_DDR3_WE_N;

// Ethernet
output					HPS_ENET_GTX_CLK;
inout						HPS_ENET_INT_N;
output					HPS_ENET_MDC;
inout						HPS_ENET_MDIO;
input						HPS_ENET_RX_CLK;
input			[ 3: 0]	HPS_ENET_RX_DATA;
input						HPS_ENET_RX_DV;
output		[ 3: 0]	HPS_ENET_TX_DATA;
output					HPS_ENET_TX_EN;

// Flash
inout			[ 3: 0]	HPS_FLASH_DATA;
output					HPS_FLASH_DCLK;
output					HPS_FLASH_NCSO;

// Accelerometer
inout						HPS_GSENSOR_INT;

// General Purpose I/O
inout			[ 1: 0]	HPS_GPIO;

// I2C
inout						HPS_I2C_CONTROL;
inout						HPS_I2C1_SCLK;
inout						HPS_I2C1_SDAT;
inout						HPS_I2C2_SCLK;
inout						HPS_I2C2_SDAT;

// Pushbutton
inout						HPS_KEY;

// LED
inout						HPS_LED;

// SD Card
output					HPS_SD_CLK;
inout						HPS_SD_CMD;
inout			[ 3: 0]	HPS_SD_DATA;

// SPI
output					HPS_SPIM_CLK;
input						HPS_SPIM_MISO;
output					HPS_SPIM_MOSI;
inout						HPS_SPIM_SS;

// UART
input						HPS_UART_RX;
output					HPS_UART_TX;

// USB
inout						HPS_CONV_USB_N;
input						HPS_USB_CLKOUT;
inout			[ 7: 0]	HPS_USB_DATA;
input						HPS_USB_DIR;
input						HPS_USB_NXT;
output					HPS_USB_STP;

//=======================================================
//  REG/WIRE declarations
//=======================================================
logic [3:0]  fpga_debounced_buttons;
logic [9:0]  fpga_led_internal;
logic        hps_fpga_reset_n;
logic [2:0]  hps_reset_req;
logic        hps_cold_reset;
logic        hps_warm_reset;
logic        hps_debug_reset;
logic [27:0] stm_hw_events;

logic [7:0] sram_address;       // Địa chỉ RAM (độ rộng tùy theo cấu hình on-chip RAM)
logic        sram_chipselect = 1'b1;        // Chip select
logic        sram_clken = 1'b1;      // Clock enable
logic        sram_write;         // Write enable
logic [31:0] sram_writedata;     // Dữ liệu ghi
logic [31:0] sram_readdata;      // Dữ liệu đọc

logic [31:0] data_buffer;
logic [31:0] data_buffer2;
logic [4:0] sram_state ;
logic [7:0] state ;
logic initEnable ;

logic [25:0] count = 26'd0;
logic led0 = 1'b0;
//=======================================================
//=======================================================
// M10K state machine
//=======================================================
// controls for M10K block just below
logic [31:0] M10K_read_data ;
logic [31:0] M10K_data_buffer, M10K_write_data ;
logic [11:0] M10K_read_address, M10K_write_address ; 
logic M10K_write ;
logic [11:0] data_size;  // Số byte, giả sử HPS viết vào addr 1
logic [31:0] data_sum;   // New: Checksum để verify data
logic [9:0] ledr_reg = 10'b0000000000;    // New: Register cho LEDR
logic [7:0] byte_value = 8'b00000000;
logic [7:0] byte_valuehex = 8'd0;
logic [3:0] byte_valuehex_1 = 4'd0;
logic [3:0] byte_valuehex_2 = 4'd0;
////////////////////////////////////////////////////////////////////
//CODING
reg [31:0] hps_to_fpga_readdata ; 
reg hps_to_fpga_read ; // read command
// status addresses
// base => fill level
// base+1 => status bits; 
//           bit0==1 if full
//           bit1==1 if empty
wire [31:0] hps_to_fpga_out_csr_address = 0 ; // fill_level
reg[31:0] hps_to_fpga_out_csr_readdata ;
reg [7:0] fill_level ;
reg hps_to_fpga_out_csr_read ; // status regs read cmd

HexDigit digit0(HEX2, byte_valuehex_1);
HexDigit digit1(HEX3, byte_valuehex_2);



always @(posedge 	CLOCK_50) begin
	if(KEY[0]) begin
		state <= 8'd0;
		sram_write <= 1'b0;
	end
	if(state == 8'd0) begin
		hps_to_fpga_out_csr_read <= 1'b1;
		sram_write <= 0;
		state <= 8'd1;
	end
	
	if(state == 8'd1) begin
		state <= 8'd2;
	end
	
	if(state == 8'd2) begin
		hps_to_fpga_out_csr_read <= 1'b0;
		if(hps_to_fpga_out_csr_readdata > 0) begin
			hps_to_fpga_read <= 1'b1;
			state <= 8'd3;
		end
		else begin
			state <= 8'd0;
		end
	end
	
	if(state == 8'd3) begin
		state <= 8'd4;
	end
		
	if(state == 8'd4) begin
		data_buffer <= hps_to_fpga_readdata;
		hps_to_fpga_read <= 1'b0;
		state <= 8'd10;
	end
	
	if(state == 8'd10) begin
		sram_address <= 8'd1;
		sram_write <= 1'b1;
		
		byte_value <= data_buffer[7:0];
		byte_valuehex_1 <= data_buffer[3:0];
		byte_valuehex_2 <= data_buffer[7:4];
		/*
		if(data_buffer == 32'd1) begin
			ledr_reg <= 10'b0000000001;
			HEX1 <= 7'b1111001;
		end else if(data_buffer == 32'd2) begin
			ledr_reg <= 10'b0000000010;
			HEX1 <= 7'b0100100;
		end else begin
			ledr_reg <= 10'b11111111111;
			HEX1 <= 7'b1111111;
		end */
		
		sram_writedata <= data_buffer;
		state <= 8'sd11;
	end
	
	if(state == 8'd11) begin
		sram_address <= 8'd0;
		sram_write <= 1'b1;
		sram_writedata <= 32'd1;
		state <= 8'd0;
	end
end
	
////////////////////////////////////////////////////////////////////

//assign HEX0 = 7'b1111111;

//assign HEX2 = byte_valuehex_1;
//assign HEX3 = byte_valuehex_2;
assign HEX4 = 7'b1111111;
assign HEX5 = 7'b1111111;
assign LEDR[7:0] = byte_value[7:0];
soc_system u0 (
	 // Ethernet
	 // Pushbutton
		  .clock_bridge_0_in_clk_clk       (CLOCK_50),
        .hps_io_hps_io_emac1_inst_TX_CLK      (HPS_ENET_GTX_CLK),      //                  hps_io.hps_io_emac1_inst_TX_CLK
        .hps_io_hps_io_emac1_inst_TXD0        (HPS_ENET_TX_DATA[0]),        //                        .hps_io_emac1_inst_TXD0
        .hps_io_hps_io_emac1_inst_TXD1        (HPS_ENET_TX_DATA[1]),        //                        .hps_io_emac1_inst_TXD1
        .hps_io_hps_io_emac1_inst_TXD2        (HPS_ENET_TX_DATA[2]),        //                        .hps_io_emac1_inst_TXD2
        .hps_io_hps_io_emac1_inst_TXD3        (HPS_ENET_TX_DATA[3]),        //                        .hps_io_emac1_inst_TXD3
        .hps_io_hps_io_emac1_inst_RXD0        (HPS_ENET_RX_DATA[0]),        //                        .hps_io_emac1_inst_RXD0
        .hps_io_hps_io_emac1_inst_MDIO        (HPS_ENET_MDIO),        //                        .hps_io_emac1_inst_MDIO
        .hps_io_hps_io_emac1_inst_MDC         (HPS_ENET_MDC),         //                        .hps_io_emac1_inst_MDC
        .hps_io_hps_io_emac1_inst_RX_CTL      (HPS_ENET_RX_DV),      //                        .hps_io_emac1_inst_RX_CTL
        .hps_io_hps_io_emac1_inst_TX_CTL      (HPS_ENET_TX_EN),      //                        .hps_io_emac1_inst_TX_CTL
        .hps_io_hps_io_emac1_inst_RX_CLK      (HPS_ENET_RX_CLK),      //                        .hps_io_emac1_inst_RX_CLK
        .hps_io_hps_io_emac1_inst_RXD1        (HPS_ENET_RX_DATA[1]),        //                        .hps_io_emac1_inst_RXD1
        .hps_io_hps_io_emac1_inst_RXD2        (HPS_ENET_RX_DATA[2]),        //                        .hps_io_emac1_inst_RXD2
        .hps_io_hps_io_emac1_inst_RXD3        (HPS_ENET_RX_DATA[3]),        //                        .hps_io_emac1_inst_RXD3
		  // Flash
        .hps_io_hps_io_qspi_inst_IO0          (HPS_FLASH_DATA[0]),          //                        .hps_io_qspi_inst_IO0
        .hps_io_hps_io_qspi_inst_IO1          (HPS_FLASH_DATA[1]),          //                        .hps_io_qspi_inst_IO1
        .hps_io_hps_io_qspi_inst_IO2          (HPS_FLASH_DATA[2]),          //                        .hps_io_qspi_inst_IO2
        .hps_io_hps_io_qspi_inst_IO3          (HPS_FLASH_DATA[3] ),          //                        .hps_io_qspi_inst_IO3
        .hps_io_hps_io_qspi_inst_SS0          (HPS_FLASH_NCSO),          //                        .hps_io_qspi_inst_SS0
        .hps_io_hps_io_qspi_inst_CLK          (HPS_FLASH_DCLK),          //                        .hps_io_qspi_inst_CLK
        .hps_io_hps_io_sdio_inst_CMD          (HPS_SD_CMD),          //                        .hps_io_sdio_inst_CMD
        .hps_io_hps_io_sdio_inst_D0           (HPS_SD_DATA[0]),           //                        .hps_io_sdio_inst_D0
        .hps_io_hps_io_sdio_inst_D1           (HPS_SD_DATA[1]),           //                        .hps_io_sdio_inst_D1
        .hps_io_hps_io_sdio_inst_CLK          (HPS_SD_CLK),          //                        .hps_io_sdio_inst_CLK
        .hps_io_hps_io_sdio_inst_D2           (HPS_SD_DATA[2]),           //                        .hps_io_sdio_inst_D2
        .hps_io_hps_io_sdio_inst_D3           (HPS_SD_DATA[3]),           //                        .hps_io_sdio_inst_D3
		  // USB
        .hps_io_hps_io_usb1_inst_D0           (HPS_USB_DATA[0]),           //                        .hps_io_usb1_inst_D0
        .hps_io_hps_io_usb1_inst_D1           (HPS_USB_DATA[1]),           //                        .hps_io_usb1_inst_D1
        .hps_io_hps_io_usb1_inst_D2           (HPS_USB_DATA[2]),           //                        .hps_io_usb1_inst_D2
        .hps_io_hps_io_usb1_inst_D3           (HPS_USB_DATA[3]),           //                        .hps_io_usb1_inst_D3
        .hps_io_hps_io_usb1_inst_D4           (HPS_USB_DATA[4]),           //                        .hps_io_usb1_inst_D4
        .hps_io_hps_io_usb1_inst_D5           (HPS_USB_DATA[5]),           //                        .hps_io_usb1_inst_D5
        .hps_io_hps_io_usb1_inst_D6           (HPS_USB_DATA[6]),           //                        .hps_io_usb1_inst_D6
        .hps_io_hps_io_usb1_inst_D7           (HPS_USB_DATA[7]),           //                        .hps_io_usb1_inst_D7
        .hps_io_hps_io_usb1_inst_CLK          (HPS_USB_CLKOUT),          //                        .hps_io_usb1_inst_CLK
        .hps_io_hps_io_usb1_inst_STP          (HPS_USB_STP),          //                        .hps_io_usb1_inst_STP
        .hps_io_hps_io_usb1_inst_DIR          (HPS_USB_DIR),          //                        .hps_io_usb1_inst_DIR
        .hps_io_hps_io_usb1_inst_NXT          (HPS_USB_NXT),          //                        .hps_io_usb1_inst_NXT
        
		  .hps_io_hps_io_spim1_inst_CLK         (HPS_SPIM_CLK),         //                        .hps_io_spim1_inst_CLK
        .hps_io_hps_io_spim1_inst_MOSI        (HPS_SPIM_MOSI),        //                        .hps_io_spim1_inst_MOSI
        .hps_io_hps_io_spim1_inst_MISO        (HPS_SPIM_MISO),        //                        .hps_io_spim1_inst_MISO
        .hps_io_hps_io_spim1_inst_SS0         (HPS_SPIM_SS),         //                        .hps_io_spim1_inst_SS0
        
		  .hps_io_hps_io_uart0_inst_RX          (HPS_UART_RX),          //                        .hps_io_uart0_inst_RX
        .hps_io_hps_io_uart0_inst_TX          (HPS_UART_TX),          //                        .hps_io_uart0_inst_TX
        
		  .hps_io_hps_io_i2c0_inst_SDA          (HPS_I2C1_SDAT),          //                        .hps_io_i2c0_inst_SDA
        .hps_io_hps_io_i2c0_inst_SCL          (HPS_I2C1_SCLK),          //                        .hps_io_i2c0_inst_SCL
        .hps_io_hps_io_i2c1_inst_SDA          (HPS_I2C2_SDAT),          //                        .hps_io_i2c1_inst_SDA
        .hps_io_hps_io_i2c1_inst_SCL          (HPS_I2C2_SCLK),          //                        .hps_io_i2c1_inst_SCL
		  // DDR3 SDRAM
        .memory_mem_a                         (HPS_DDR3_ADDR),                         //                  memory.mem_a
        .memory_mem_ba                        (HPS_DDR3_BA),                        //                        .mem_ba
        .memory_mem_ck                        (HPS_DDR3_CK_P),                        //                        .mem_ck
        .memory_mem_ck_n                      (HPS_DDR3_CK_N),                      //                        .mem_ck_n
        .memory_mem_cke                       (HPS_DDR3_CKE),                       //                        .mem_cke
        .memory_mem_cs_n                      (HPS_DDR3_CS_N),                      //                        .mem_cs_n
        .memory_mem_ras_n                     (HPS_DDR3_RAS_N),                     //                        .mem_ras_n
        .memory_mem_cas_n                     (HPS_DDR3_CAS_N),                     //                        .mem_cas_n
        .memory_mem_we_n                      (HPS_DDR3_WE_N),                      //                        .mem_we_n
        .memory_mem_reset_n                   (HPS_DDR3_RESET_N),                   //                        .mem_reset_n
        .memory_mem_dq                        (HPS_DDR3_DQ),                        //                        .mem_dq
        .memory_mem_dqs                       (HPS_DDR3_DQS_P),                       //                        .mem_dqs
        .memory_mem_dqs_n                     (HPS_DDR3_DQS_N),                     //                        .mem_dqs_n
        .memory_mem_odt                       (HPS_DDR3_ODT),                       //                        .mem_odt
        .memory_mem_dm                        (HPS_DDR3_DM),                        //                        .mem_dm
        .memory_oct_rzqin                     (HPS_DDR3_RZQ),                     //                        .oct_rzqin
		  
        .onchip_memory2_0_s1_address          (sram_address),          //     onchip_memory2_0_s2.address
        .onchip_memory2_0_s1_chipselect       (sram_chipselect),       //                        .chipselect
        .onchip_memory2_0_s1_clken            (sram_clken),            //                        .clken
        .onchip_memory2_0_s1_write            (sram_write),            //                        .write
        .onchip_memory2_0_s1_readdata         (sram_readdata),         //                        .readdata
        .onchip_memory2_0_s1_writedata        (sram_writedata),        //                        .writedata
        .onchip_memory2_0_s1_byteenable       (4'b1111),       //                        .byteenable
		  
		  .sys_sdram_pll_0_ref_clk_clk          (CLOCK_50),          //   sys_sdram_pll_0_ref_clk.clk
        .sys_sdram_pll_0_ref_reset_reset      (1'b0),
		  
        .fifo_hps_to_fpga_out_csr_address   (hps_to_fpga_out_csr_address),   //  fifo_hps_to_fpga_out_csr.address
        .fifo_hps_to_fpga_out_csr_read      (hps_to_fpga_out_csr_read),      //                          .read
        .fifo_hps_to_fpga_out_csr_writedata (), //                          .writedata
        .fifo_hps_to_fpga_out_csr_write     (1'b0),     //                          .write
        .fifo_hps_to_fpga_out_csr_readdata  (hps_to_fpga_out_csr_readdata),  //                          .readdata
        .fifo_hps_to_fpga_out_readdata      (hps_to_fpga_readdata),      //      fifo_hps_to_fpga_out.readdata
        .fifo_hps_to_fpga_out_read          (hps_to_fpga_read),          //                          .read
        .fifo_hps_to_fpga_out_waitrequest   ()    //                          .waitrequest
        
    );


endmodule
